version: '3.3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      assignment-network:
        aliases:
          - redis

  userms_db:
    image: postgres:11.8
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=assignment_local
    networks:
      assignment-network:
        aliases:
          - userms_db
networks:
  assignment-network:
    driver: bridge