spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/assignment_local}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_SEC:docker}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
    open-in-view: off
  liquibase:
    change-log: classpath:db.changelog/changelog-master.yml
    enabled: true

