spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/assignment_local}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_SEC:docker}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      "hibernate.jdbc.lob.non_contextual_creation": true
    database-platform: org.hibernate.dialect.ProgressDialect
    hibernate:
      ddl-auto: update
    show-sql: true
